 # -*- mode: ruby -*-
 # vi: set ft=ruby :



Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8s"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus   = 1
    end

    config.vm.define "slave1.puppet" do |slave|
        slave.vm.network "private_network", ip: "192.168.56.6"
        slave.vm.hostname = "slave1.puppet"

    end

    config.vm.define "slave2.puppet" do |slave|
        slave.vm.network "private_network", ip: "192.168.56.7"
        slave.vm.hostname = "slave2.puppet"

    end

    config.vm.define "mineserver.puppet" do |slave|
        slave.vm.network "private_network", ip: "192.168.56.8"
        slave.vm.hostname = "mineserver.puppet"
        slave.vm.provider("virtualbox") { |vb| vb.memory = 2048 }
    end

    config.vm.define "master.puppet", primary: true do |master|
        master.vm.network "private_network", ip: "192.168.56.5"
        master.vm.hostname = "master.puppet"
        master.vm.provider("virtualbox") { |vb| vb.memory = 1512 }

        master.vm.provision :file, source: '.vagrant/machines/slave1.puppet/virtualbox/private_key', destination: '/home/vagrant/private_key_slave1'
        master.vm.provision :file, source: '.vagrant/machines/slave2.puppet/virtualbox/private_key', destination: '/home/vagrant/private_key_slave2'
        master.vm.provision :file, source: '.vagrant/machines/mineserver.puppet/virtualbox/private_key', destination: '/home/vagrant/private_key_mineserver'       
        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.limit = "all"
            ansible.inventory_path = "inventory"
      end 
   end
end
