pipeline {
  
  agent any
  
  tools {
            go 'Go 1.16'
        }

  environment {
      NEXUS_IP="localhost"
  }

  options {
      timestamps()
  }

  stages{
      stage ('source code download'){
        steps{
            cleanWs()
            git(
                branch: 'master',
                changelog: false,
                poll: false,
                url: 'https://github.com/malec0101/word-cloud-generator.git'
            )
        }
    }
  
      stage ('source code checking'){
        steps{
	    sh '''
	       make lint
	       make test
	    '''
        }
    }
    
      stage ('Build code'){
        steps{
            sh '''
                echo "{ \\"version\\": \\"1.$BUILD_NUMBER\\" }" >static/version

                GOOS=linux GOARCH=amd64 go build -o ./artifacts/word-cloud-generator -v .

                md5sum artifacts/word-cloud-generator
                gzip artifacts/word-cloud-generator

                ls -l artifacts/
            '''
            nexusArtifactUploader  (
                artifacts: [
                    [
                        artifactId: 'word-cloud-generator', 
                        classifier: '', 
                        file: 'artifacts/word-cloud-generator.gz', 
                        type: 'gz'
                    ]
                ], 
                credentialsId: 'nexus-creds', 
                groupId: '1', 
                nexusUrl: "$NEXUS_IP:81/", 
                nexusVersion: 'nexus3', 
                protocol: 'http', 
                repository: 'word-cloud-app', 
                version: '$BUILD_NUMBER'
            )
        }
     }  
   }	
}
