 # -*- mode: ruby -*-
 # vi: set ft=ruby :

jenkins_ip    = "192.168.56.5"
nexus_ip      = "192.168.56.6"
staging_ip    = "192.168.56.7"
production_ip = "192.168.56.8"

Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  "./", "/vagrant", create: true, disabled: false


    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus   = 1 
    end


    config.vm.define "nexus.vm" do |nexus|
        nexus.vm.network "private_network", ip: nexus_ip
        nexus.vm.hostname = "nexus.vm"
        nexus.vm.provider("virtualbox") { |vb| vb.memory = 1024 }

    end

    config.vm.define "staging.vm" do |staging|
        staging.vm.network "private_network", ip: staging_ip
        staging.vm.hostname = "staging.vm"

    end

    config.vm.define "production.vm" do |production|
        production.vm.network "private_network", ip: production_ip
        production.vm.hostname = "production.vm"
    end


    config.vm.define "jenkins.vm", primary: true do |jenkins|
        jenkins.vm.network "private_network", ip: jenkins_ip
        jenkins.vm.hostname = "jenkins.vm"
        jenkins.vm.provider("virtualbox") { |vb| vb.memory = 1024 }

        jenkins.vm.provision :file, source: '.vagrant/machines/nexus.vm/virtualbox/private_key', destination: '/home/vagrant/private_key_nexus'
        jenkins.vm.provision :file, source: '.vagrant/machines/staging.vm/virtualbox/private_key', destination: '/home/vagrant/private_key_staging'
        jenkins.vm.provision :file, source: '.vagrant/machines/production.vm/virtualbox/private_key', destination: '/home/vagrant/private_key_production'

        jenkins.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.limit = "all"
            ansible.host_vars = {
              "jenkins.vm"    => {"ansible_host": jenkins_ip},
              "nexus.vm"      => {"ansible_host": nexus_ip,
                 "ansible_ssh_private_key_file" => "/home/vagrant/private_key_nexus"
              },
              "staging.vm"    => {"ansible_host": staging_ip,
                 "ansible_ssh_private_key_file" => "/home/vagrant/private_key_staging" 
              },
              "production.vm" => {"ansible_host": production_ip,
                 "ansible_ssh_private_key_file" => "/home/vagrant/private_key_production"
              },
            }
            ansible.groups = {
              "environments" => ["staging.vm", "production.vm"],
              "all:vars" => {
                "ansible_connection": "ssh",
                "ansible_user": "vagrant",
                "ansible_ssh_common_args": "-o StrictHostKeyChecking=no",
                "jenkins_ip": jenkins_ip,
                "nexus_ip":   nexus_ip,
                "staging_ip": staging_ip,
                "production_ip": production_ip
              }
            }
      end      
   end
end 

