 # -*- mode: ruby -*-
 # vi: set ft=ruby :

jenkins_ip             = "192.168.56.5"
jenkins_admin_username = "admin" 
jenkins_admin_password = "admin"

nexus_ip               = "192.168.56.6"
nexus_admin_password   = "admin"

staging_ip             = "192.168.56.7"
production_ip          = "192.168.56.8"

Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  "./", "/vagrant", create: true, disabled: false


    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus   = 1 
    end


    config.vm.define "nexus.vm" do |nexus|
        nexus.vm.network "private_network", ip: nexus_ip
        nexus.vm.hostname = "nexus.vm"
        nexus.vm.provider("virtualbox") { |vb| vb.memory = 1024 }
        nexus.vm.provision "shell", inline: <<-SHELL
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
            sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            service sshd restart
        SHELL
    end

    config.vm.define "staging.vm" do |staging|
        staging.vm.network "private_network", ip: staging_ip
        staging.vm.hostname = "staging.vm"
        staging.vm.provision "shell", inline: <<-SHELL
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
            sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            service sshd restart
        SHELL
    end

    config.vm.define "production.vm" do |production|
        production.vm.network "private_network", ip: production_ip
        production.vm.hostname = "production.vm"
        production.vm.provision "shell", inline: <<-SHELL
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
            sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            service sshd restart
        SHELL
    end


    config.vm.define "jenkins.vm", primary: true do |jenkins|
        jenkins.vm.network "private_network", ip: jenkins_ip
        jenkins.vm.hostname = "jenkins.vm"
        jenkins.vm.provider("virtualbox") { |vb| vb.memory = 1024 }
        jenkins.vm.provision "shell", inline: <<-SHELL
            apt install -y sshpass
            sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
            sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
            sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
            service sshd restart
        SHELL
        jenkins.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.limit = "all"
            ansible.host_vars = {
              "jenkins.vm"    => {"ansible_host": jenkins_ip,
                "jenkins_admin_username": jenkins_admin_username,
                "jenkins_admin_password": jenkins_admin_password
              },
              "nexus.vm"      => {"ansible_host": nexus_ip,
                "nexus_admin_password": nexus_admin_password,
              },
              "staging.vm"    => {"ansible_host": staging_ip},
              "production.vm" => {"ansible_host": production_ip},
            }
            ansible.groups = {
              "environments" => ["staging.vm", "production.vm"],
              "all:vars" => {
                "ansible_connection":      "ssh",
                "ansible_user":            "vagrant",
                "ansible_password":        "vagrant",
                "ansible_ssh_common_args": "-o StrictHostKeyChecking=no",
                "jenkins_ip":              jenkins_ip,
                "nexus_ip":                nexus_ip,
                "staging_ip":              staging_ip,
                "production_ip":           production_ip
              }
            }
      end      
   end
end
