---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wcg
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://malec0101.github.io/devops-hometasks/'
    targetRevision: 1.0.3
    chart: word-cloud-generator
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true    
