---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: wcg
  repo: https://malec0101.github.io/devops-hometasks
  version: "1.0.2"
  releaseName: word-cloud-generator
  namespace: default
  valuesFile: values.yaml
