replicas: 3

service:
  externalPort: 8888
  internalPort: 8888  

container:
  port: 8888
  name: wcg

image:
  imageRegistry: ghcr.io
  repository: malec0101
  tag: latest

ingress:
  type: ClusterIP
  nameIngress: wcg-ingress
  annotations:
    rewrite_target: / # nginx.ingress.kubernetes.io/rewrite-target
  host: wcg.by
  path: /
  pathType: Prefix
