apiVersion: v1
kind: Service
metadata:
  name: {{ template "wcg.name" . }}-svc
  labels:
    app: {{ template "wcg.name" . }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ template "wcg.name" . }}
