name: CI World-cloud-generator

on:
  pull_request:
    types: 
      - closed
    branches:
      - feature
  workflow_dispatch:
permissions:
    contents: write
    packages: write   
    pages: write  

env:
  NAME_IMAGE: wcg
  VERSION_IMAGE: latest
  URL_DOCKERFILE: https://raw.githubusercontent.com/malec0101/devops-hometasks/main/07-docker/Dockerfile.multi
  ACTION_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  TAG_INITIAL_VERSION: 1.1.6
  TAG_DEFAULT_BUMP: patch  
  TAG_BRANCHES: main # the name of the branch to which the tag will be applied
  TAG_PRERELEASE: false # appl tag PRERELEASE 

  CHARTS_DIR: 12-helm/wcg  

jobs:
  CI:
    #if: github.event.pull_request.merged == true 
   runs-on: ubuntu-latest
   steps:
     -
       uses: actions/checkout@v3
       with:
         ref: ${{ github.event.pull_request.merge_commit_sha }}
         fetch-depth: '0'
     -
       name: Bump version and push tag
       id: tag_version  
       uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
           #WITH_V: true
         DEFAULT_BUMP: ${{ env.TAG_DEFAULT_BUMP }}  
         INITIAL_VERSION: ${{ env.TAG_INITIAL_VERSION }}  
         PRERELEASE: ${{ env.TAG_PRERELEASE }}
         RELEASE_BRANCHES: ${{ env.TAG_BRANCHES }}  
         NONE_STRING_TOKEN: ${{ github.run_number }}"  
     -
      id: string
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ github.repository_owner }}
     -
       name: Login to GitHub Package Registry
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ env.ACTION_TOKEN }}
     - 
       name: Build and push
       uses: docker/build-push-action@v5
       with:
         context: ${{ env.URL_DOCKERFILE }}
         platforms: linux/amd64
         push: true
         tags: |
           ghcr.io/${{ steps.string.outputs.lowercase }}/${{ env.NAME_IMAGE }}:${{ env.VERSION_IMAGE }}
           ghcr.io/${{ steps.string.outputs.lowercase }}/${{ env.NAME_IMAGE }}:${{ steps.tag_version.outputs.new_tag }}
           ghcr.io/${{ steps.string.outputs.lowercase }}/${{ env.NAME_IMAGE }}:${{ github.sha }}          
     -
       name: Checkout
       uses: actions/checkout@v3      
       with:
          fetch-depth: 0  
     -
       name: Set up Helm
       uses: azure/setup-helm@v3
       with:
         version: v3.12.1
     -  
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'
         check-latest: true
     -
       name: Run chart-testing (lint)
       run: heln lint ${{ env.CHARTS_DIR }} 
     -
       name: Checkout
       uses: actions/checkout@v3 
       with:
          fetch-depth: 0
     -
       name: Configure Git
       run: |
             git config user.name "$GITHUB_ACTOR"
             git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
     -
       name: Run chart-releaser
       uses: helm/chart-releaser-action@v1.6.0
       env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true  
       with:     
          charts_dir: ${{ env.CHARTS_DIR }}
          packages_with_index:
          pages_branch: gh-pages 
          config: cr.yaml
