name: CI World-cloud-generator

on:
  push:
  workflow_dispatch:

env:
  NAME_IMAGE: wcg
  VERSION_IMAGE: latest
  URL_DOCKERFILE: https://raw.githubusercontent.com/malec0101/devops-hometasks/main/07-docker/Dockerfile.multi
  ACTION_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Build_Push:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
   steps:
     -
       id: string
       uses: ASzc/change-string-case-action@v6
       with:
         string: ${{ github.repository_owner }}
     -
       name: Login to GitHub Package Registry
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ env.ACTION_TOKEN }}
     - 
       name: Build and push
       uses: docker/build-push-action@v5
       with:
         context: ${{ env.URL_DOCKERFILE }}
         platforms: linux/amd64
         push: true
         tags: |
           ghcr.io/${{ steps.string.outputs.lowercase }}/${{ env.NAME_IMAGE }}:${{ env.VERSION_IMAGE }}
           ghcr.io/${{ steps.string.outputs.lowercase }}/${{ env.NAME_IMAGE }}:${{ github.sha }}
