name: CI World-cloud-generator

on:
  push:
  workflow_dispatch:

env:
  NAME_IMAGE: wcg
  VERSION_IMAGE: latest
  URL_DOCKERFILE: https://raw.githubusercontent.com/malec0101/devops-hometasks/main/07-docker/Dockerfile.multi

jobs:
  Build_Push:
   runs-on: self-hosted
   steps:
     -
       name: Login to GitHub Package Registry
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - 
       #       run: |
       #     echo "----
       #     Download Dockerfile
       #     --->"
       #     curl -O https://raw.githubusercontent.com/malec0101/devops-hometasks/main/07-docker/Dockerfile.multi
       #     echo "----
       #     Build image
       #     --->"
       #     docker build \
       #     -t ${{ env.NAME_IMAGE }}:${{ env.VERSION_IMAGE }} \
       #     -t ${{ env.NAME_IMAGE }}:${{ github.sha }} \
       #     -f Dockerfile.multi .
     
       name: Build and push
       uses: docker/build-push-action@v5
       with:
         context: ${{ env.URL_DOCKERFILE }}
         platforms: linux/amd64
         push: true
         tags: |
           ghcr.io/${{ github.repository_owner }}/${{ env.NAME_IMAGE }}:${{ env.VERSION_IMAGE }}
           ghcr.io/${{ github.repository_owner }}/${{ env.NAME_IMAGE }}:${{ github.sha }}
